/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.pe.tocgic.tools.strresparser.view;

import kr.pe.tocgic.tools.strresparser.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
